### ISSUE TITLE
h5py version should be specified

### ISSUE THREAD

**Issue by mfansler** [johli/aparent-resnet#1]
For `keras==2.2.4`, I find the `load_model` fails unless `h5py` is version 2 (specifically, I have it working with `h5py==2.10.0`). Otherwise, the error one encounters is similar to that in [this StackOverflow post](https://stackoverflow.com/q/53740577/570918).

I suggest a working `h5py` version be specified in the README to preempt others running into this issue.

**Comment by johli** [comment]
Thank you for bringing this to attention, really appreciate it! I'll add it to the readme.
