### ISSUE TITLE
EOF on saved models

### ISSUE THREAD

**Issue by ezecalvo** [johli/aparent-resnet#3]
Hi,

I'm trying to replicate [this](https://github.com/johli/aparent-resnet/blob/master/examples/aparent2_score_variants.ipynb) notebook but keep getting an EOF error when loading the aparent_all_libs_resnet_no_clinvar_wt_ep_5_var_batch_size_inference_mode_no_drop model from the saved_models.

For example:

`aparent_model = load_model('path/to/saved_models/aparent_all_libs_resnet_no_clinvar_wt_ep_5_var_batch_size_inference_mode_no_drop.h5',compile=False)`

`EOFError: EOF read where object expected`

I get the same error in all the other models except aparent_all_libs_convnet_no_clinvar_wt_ep_19. Maybe I'm missing something?

Thanks!

Edit: the problem was me being silly and not having the right package versions!

**Comment by johli** [comment]
Glad it worked out! FYI I will try to manually convert the models to tensorflow 2 objects soon.

Best,

Johannes
